/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "SmartCity.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(akita_smart_city_SmartCityPacket, akita_smart_city_SmartCityPacket, AUTO)


PB_BIND(akita_smart_city_ServiceDiscovery, akita_smart_city_ServiceDiscovery, AUTO)


PB_BIND(akita_smart_city_SensorData, akita_smart_city_SensorData, AUTO)


PB_BIND(akita_smart_city_SensorData_ReadingsEntry, akita_smart_city_SensorData_ReadingsEntry, AUTO)





