/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AKITA_SMART_CITY_SMARTCITY_PB_H_INCLUDED
#define PB_AKITA_SMART_CITY_SMARTCITY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Defines the primary function of the node in the ASCS network. */
typedef enum _akita_smart_city_ServiceDiscovery_Role {
    akita_smart_city_ServiceDiscovery_Role_UNKNOWN = 0, /* Default/initial state */
    akita_smart_city_ServiceDiscovery_Role_SENSOR = 1, /* Collects data from physical sensors */
    akita_smart_city_ServiceDiscovery_Role_AGGREGATOR = 2, /* Relays data from sensors towards gateways (optional role) */
    akita_smart_city_ServiceDiscovery_Role_GATEWAY = 3 /* Bridges Meshtastic network to external systems (e.g., MQTT) */
} akita_smart_city_ServiceDiscovery_Role;

typedef enum _akita_smart_city_ControlAck_Status {
    akita_smart_city_ControlAck_Status_REJECTED = 0,
    akita_smart_city_ControlAck_Status_EXECUTED = 1,
    akita_smart_city_ControlAck_Status_FAILED = 2
} akita_smart_city_ControlAck_Status;

/* Struct definitions */
/* Used for nodes to announce their roles and capabilities periodically. */
typedef struct _akita_smart_city_ServiceDiscovery {
    akita_smart_city_ServiceDiscovery_Role node_role; /* The role this node is configured for. */
    uint32_t service_id; /* Optional identifier for specific services/groups/locations. */
} akita_smart_city_ServiceDiscovery;

/* Flexible sensor data structure. Sent by Sensor nodes, potentially relayed
 by Aggregators, and consumed by Gateways. */
typedef struct _akita_smart_city_SensorData {
    /* Optional: Identifier for the specific sensor type or location (e.g., "BME280-Floor1", "ParkingLot-A7").
 Useful when a single node has multiple sensors or for context. */
    char sensor_id[65];
    /* Timestamp (Unix epoch seconds) when the reading was taken.
 Helps ensure data is correctly ordered and timestamped, independent of mesh delays. */
    uint32_t timestamp_utc;
    /* Flexible key-value map for sensor readings.
 Keys describe the reading (e.g., "temperature_c", "humidity_pct", "pressure_pa", "battery_v", "door_open").
 Values are float, suitable for many sensor types. Use specific conventions (e.g., 1.0 for true/open). */
    pb_callback_t readings;
    /* Optional: Sequence number from the sensor node to help detect missed packets on the receiver side. */
    uint32_t sequence_num;
    /* Mesh node that collected the reading. Aggregators preserve this identity when relaying. */
    uint32_t origin_node;
} akita_smart_city_SensorData;

typedef struct _akita_smart_city_SensorData_ReadingsEntry {
    pb_callback_t key;
    float value;
} akita_smart_city_SensorData_ReadingsEntry;

typedef struct _akita_smart_city_ControlCommand {
    char command_id[37];
    uint32_t target_node;
    char asset_id[65];
    char action[33];
    pb_size_t which_value;
    union {
        bool bool_value;
        float numeric_value;
    } value;
    uint32_t expires_at_utc;
} akita_smart_city_ControlCommand;

typedef struct _akita_smart_city_ControlAck {
    char command_id[37];
    akita_smart_city_ControlAck_Status status;
    char detail[97];
} akita_smart_city_ControlAck;

/* Main message wrapper for all ASCS communication over Meshtastic.
 Uses a specific Meshtastic port number (defined in the C++ code). */
typedef struct _akita_smart_city_SmartCityPacket {
    pb_size_t which_payload;
    union {
        akita_smart_city_ServiceDiscovery discovery; /* For announcing/discovering node roles */
        akita_smart_city_SensorData sensor_data; /* For transmitting sensor readings */
        akita_smart_city_ControlCommand control_command; /* Authenticated operator command routed by a gateway */
        akita_smart_city_ControlAck control_ack; /* Device execution result returned to a gateway */
    } payload;
} akita_smart_city_SmartCityPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _akita_smart_city_ServiceDiscovery_Role_MIN akita_smart_city_ServiceDiscovery_Role_UNKNOWN
#define _akita_smart_city_ServiceDiscovery_Role_MAX akita_smart_city_ServiceDiscovery_Role_GATEWAY
#define _akita_smart_city_ServiceDiscovery_Role_ARRAYSIZE ((akita_smart_city_ServiceDiscovery_Role)(akita_smart_city_ServiceDiscovery_Role_GATEWAY+1))

#define _akita_smart_city_ControlAck_Status_MIN akita_smart_city_ControlAck_Status_REJECTED
#define _akita_smart_city_ControlAck_Status_MAX akita_smart_city_ControlAck_Status_FAILED
#define _akita_smart_city_ControlAck_Status_ARRAYSIZE ((akita_smart_city_ControlAck_Status)(akita_smart_city_ControlAck_Status_FAILED+1))


#define akita_smart_city_ServiceDiscovery_node_role_ENUMTYPE akita_smart_city_ServiceDiscovery_Role




#define akita_smart_city_ControlAck_status_ENUMTYPE akita_smart_city_ControlAck_Status


/* Initializer values for message structs */
#define akita_smart_city_SmartCityPacket_init_default {0, {akita_smart_city_ServiceDiscovery_init_default}}
#define akita_smart_city_ServiceDiscovery_init_default {_akita_smart_city_ServiceDiscovery_Role_MIN, 0}
#define akita_smart_city_SensorData_init_default {"", 0, {{NULL}, NULL}, 0, 0}
#define akita_smart_city_SensorData_ReadingsEntry_init_default {{{NULL}, NULL}, 0}
#define akita_smart_city_ControlCommand_init_default {"", 0, "", "", 0, {0}, 0}
#define akita_smart_city_ControlAck_init_default {"", _akita_smart_city_ControlAck_Status_MIN, ""}
#define akita_smart_city_SmartCityPacket_init_zero {0, {akita_smart_city_ServiceDiscovery_init_zero}}
#define akita_smart_city_ServiceDiscovery_init_zero {_akita_smart_city_ServiceDiscovery_Role_MIN, 0}
#define akita_smart_city_SensorData_init_zero    {"", 0, {{NULL}, NULL}, 0, 0}
#define akita_smart_city_SensorData_ReadingsEntry_init_zero {{{NULL}, NULL}, 0}
#define akita_smart_city_ControlCommand_init_zero {"", 0, "", "", 0, {0}, 0}
#define akita_smart_city_ControlAck_init_zero    {"", _akita_smart_city_ControlAck_Status_MIN, ""}

/* Field tags (for use in manual encoding/decoding) */
#define akita_smart_city_ServiceDiscovery_node_role_tag 1
#define akita_smart_city_ServiceDiscovery_service_id_tag 2
#define akita_smart_city_SensorData_sensor_id_tag 1
#define akita_smart_city_SensorData_timestamp_utc_tag 2
#define akita_smart_city_SensorData_readings_tag 3
#define akita_smart_city_SensorData_sequence_num_tag 4
#define akita_smart_city_SensorData_origin_node_tag 5
#define akita_smart_city_SensorData_ReadingsEntry_key_tag 1
#define akita_smart_city_SensorData_ReadingsEntry_value_tag 2
#define akita_smart_city_ControlCommand_command_id_tag 1
#define akita_smart_city_ControlCommand_target_node_tag 2
#define akita_smart_city_ControlCommand_asset_id_tag 3
#define akita_smart_city_ControlCommand_action_tag 4
#define akita_smart_city_ControlCommand_bool_value_tag 5
#define akita_smart_city_ControlCommand_numeric_value_tag 6
#define akita_smart_city_ControlCommand_expires_at_utc_tag 7
#define akita_smart_city_ControlAck_command_id_tag 1
#define akita_smart_city_ControlAck_status_tag   2
#define akita_smart_city_ControlAck_detail_tag   3
#define akita_smart_city_SmartCityPacket_discovery_tag 1
#define akita_smart_city_SmartCityPacket_sensor_data_tag 2
#define akita_smart_city_SmartCityPacket_control_command_tag 3
#define akita_smart_city_SmartCityPacket_control_ack_tag 4

/* Struct field encoding specification for nanopb */
#define akita_smart_city_SmartCityPacket_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,discovery,payload.discovery),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,sensor_data,payload.sensor_data),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,control_command,payload.control_command),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,control_ack,payload.control_ack),   4)
#define akita_smart_city_SmartCityPacket_CALLBACK NULL
#define akita_smart_city_SmartCityPacket_DEFAULT NULL
#define akita_smart_city_SmartCityPacket_payload_discovery_MSGTYPE akita_smart_city_ServiceDiscovery
#define akita_smart_city_SmartCityPacket_payload_sensor_data_MSGTYPE akita_smart_city_SensorData
#define akita_smart_city_SmartCityPacket_payload_control_command_MSGTYPE akita_smart_city_ControlCommand
#define akita_smart_city_SmartCityPacket_payload_control_ack_MSGTYPE akita_smart_city_ControlAck

#define akita_smart_city_ServiceDiscovery_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    node_role,         1) \
X(a, STATIC,   SINGULAR, UINT32,   service_id,        2)
#define akita_smart_city_ServiceDiscovery_CALLBACK NULL
#define akita_smart_city_ServiceDiscovery_DEFAULT NULL

#define akita_smart_city_SensorData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   sensor_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_utc,     2) \
X(a, CALLBACK, REPEATED, MESSAGE,  readings,          3) \
X(a, STATIC,   SINGULAR, UINT32,   sequence_num,      4) \
X(a, STATIC,   SINGULAR, UINT32,   origin_node,       5)
#define akita_smart_city_SensorData_CALLBACK pb_default_field_callback
#define akita_smart_city_SensorData_DEFAULT NULL
#define akita_smart_city_SensorData_readings_MSGTYPE akita_smart_city_SensorData_ReadingsEntry

#define akita_smart_city_SensorData_ReadingsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             2)
#define akita_smart_city_SensorData_ReadingsEntry_CALLBACK pb_default_field_callback
#define akita_smart_city_SensorData_ReadingsEntry_DEFAULT NULL

#define akita_smart_city_ControlCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   command_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   target_node,       2) \
X(a, STATIC,   SINGULAR, STRING,   asset_id,          3) \
X(a, STATIC,   SINGULAR, STRING,   action,            4) \
X(a, STATIC,   ONEOF,    BOOL,     (value,bool_value,value.bool_value),   5) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,numeric_value,value.numeric_value),   6) \
X(a, STATIC,   SINGULAR, UINT32,   expires_at_utc,    7)
#define akita_smart_city_ControlCommand_CALLBACK NULL
#define akita_smart_city_ControlCommand_DEFAULT NULL

#define akita_smart_city_ControlAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   command_id,        1) \
X(a, STATIC,   SINGULAR, UENUM,    status,            2) \
X(a, STATIC,   SINGULAR, STRING,   detail,            3)
#define akita_smart_city_ControlAck_CALLBACK NULL
#define akita_smart_city_ControlAck_DEFAULT NULL

extern const pb_msgdesc_t akita_smart_city_SmartCityPacket_msg;
extern const pb_msgdesc_t akita_smart_city_ServiceDiscovery_msg;
extern const pb_msgdesc_t akita_smart_city_SensorData_msg;
extern const pb_msgdesc_t akita_smart_city_SensorData_ReadingsEntry_msg;
extern const pb_msgdesc_t akita_smart_city_ControlCommand_msg;
extern const pb_msgdesc_t akita_smart_city_ControlAck_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define akita_smart_city_SmartCityPacket_fields &akita_smart_city_SmartCityPacket_msg
#define akita_smart_city_ServiceDiscovery_fields &akita_smart_city_ServiceDiscovery_msg
#define akita_smart_city_SensorData_fields &akita_smart_city_SensorData_msg
#define akita_smart_city_SensorData_ReadingsEntry_fields &akita_smart_city_SensorData_ReadingsEntry_msg
#define akita_smart_city_ControlCommand_fields &akita_smart_city_ControlCommand_msg
#define akita_smart_city_ControlAck_fields &akita_smart_city_ControlAck_msg

/* Maximum encoded size of messages (where known) */
/* akita_smart_city_SmartCityPacket_size depends on runtime parameters */
/* akita_smart_city_SensorData_size depends on runtime parameters */
/* akita_smart_city_SensorData_ReadingsEntry_size depends on runtime parameters */
#define AKITA_SMART_CITY_SMARTCITY_PB_H_MAX_SIZE akita_smart_city_ControlCommand_size
#define akita_smart_city_ControlAck_size         138
#define akita_smart_city_ControlCommand_size     155
#define akita_smart_city_ServiceDiscovery_size   8

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
