#pragma once

#define ASCS_PROVISION_SCHEMA_VERSION 1U
#define ASCS_PROVISION_ROLE 3U
#define ASCS_PROVISION_SERVICE_ID 1U
#define ASCS_PROVISION_TARGET_NODE 0U
#define ASCS_PROVISION_TRUSTED_GATEWAY_NODE 0U
#define ASCS_PROVISION_READ_INTERVAL_MS 60000U
#define ASCS_PROVISION_DISCOVERY_INTERVAL_MS 300000U
#define ASCS_PROVISION_SERVICE_TIMEOUT_MS 900000U
#define ASCS_PROVISION_MQTT_RECONNECT_MS 10000U

#define ASCS_PROVISION_WIFI_SSID ""
#define ASCS_PROVISION_WIFI_PASSWORD ""
#define ASCS_PROVISION_MQTT_SERVER ""
#define ASCS_PROVISION_MQTT_PORT 8883U
#define ASCS_PROVISION_MQTT_USER ""
#define ASCS_PROVISION_MQTT_PASSWORD ""
#define ASCS_PROVISION_MQTT_TOPIC "akita/smartcity"
#define ASCS_PROVISION_MQTT_CA_CERT ""
