#!/usr/bin/env python3
"""Install ASCS into a checked-out Meshtastic firmware tree."""

from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path


INCLUDE_BLOCK = """#ifdef ASCS_OFFICIAL_FIRMWARE
#include \"modules/ascs/AkitaSmartCityServices.h\"
#endif
"""
SETUP_BLOCK = """#ifdef ASCS_OFFICIAL_FIRMWARE
    new AkitaSmartCityServices();
#endif
"""


def insert_once(text: str, anchor: str, block: str, *, after: bool) -> str:
    if block.strip() in text:
        return text
    index = text.find(anchor)
    if index < 0:
        raise RuntimeError(f"Meshtastic integration anchor was not found: {anchor!r}")
    index = index + len(anchor) if after else index
    return text[:index] + ("\n" if after else "") + block + text[index:]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("firmware", type=Path, help="Meshtastic firmware checkout")
    parser.add_argument("--base-env", required=True, help="Existing Meshtastic PlatformIO environment")
    parser.add_argument("--role", choices=("sensor", "aggregator", "gateway"), required=True)
    parser.add_argument("--sensor", choices=("bme280",), help="Concrete sensor driver for sensor role")
    args = parser.parse_args()

    if args.role == "sensor" and args.sensor is None:
        parser.error("--sensor is required for sensor role")
    if args.role != "sensor" and args.sensor is not None:
        parser.error("--sensor is only valid for sensor role")
    if not re.fullmatch(r"[A-Za-z0-9_.-]+", args.base_env):
        parser.error("--base-env may contain only letters, digits, dots, underscores, and hyphens")

    repository = Path(__file__).resolve().parents[1]
    firmware = args.firmware.resolve()
    modules = firmware / "src" / "modules"
    modules_cpp = modules / "Modules.cpp"
    platformio = firmware / "platformio.ini"
    if not modules_cpp.is_file() or not platformio.is_file():
        parser.error("firmware must be the root of a Meshtastic firmware checkout")

    source = modules_cpp.read_text(encoding="utf-8")
    source = insert_once(source, '#include "configuration.h"', INCLUDE_BLOCK, after=True)
    source = insert_once(source, "void setupModules()\n{", SETUP_BLOCK, after=True)

    destination = modules / "ascs"
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(repository / "src", destination)
    modules_cpp.write_text(source, encoding="utf-8")

    role_macro = {
        "sensor": "ServiceDiscovery_Role_SENSOR",
        "aggregator": "ServiceDiscovery_Role_AGGREGATOR",
        "gateway": "ServiceDiscovery_Role_GATEWAY",
    }[args.role]
    environment = f"ascs-{args.base_env}-{args.role}"
    flags = [
        "  -D ASCS_OFFICIAL_FIRMWARE",
        f"  -D ASCS_DEFAULT_ROLE={role_macro}",
        "  -fno-strict-aliasing",
    ]
    if args.role == "gateway":
        flags.append("  -D ASCS_ROLE_GATEWAY")
    if args.sensor == "bme280":
        flags.append("  -D ASCS_SENSOR_BME280")

    variant_directory = firmware / "variants" / "ascs"
    variant_directory.mkdir(parents=True, exist_ok=True)
    dependencies = [f"  ${{env:{args.base_env}.lib_deps}}"]
    if args.role == "gateway":
        dependencies.append("  bblanchon/ArduinoJson@6.21.6")
    if args.sensor == "bme280":
        dependencies.append("  adafruit/Adafruit BME280 Library@2.3.0")

    legacy_environment = variant_directory / "platformio.ini"
    if legacy_environment.is_file():
        legacy_text = legacy_environment.read_text(encoding="utf-8")
        if legacy_text.startswith("[env:ascs-") and "-D ASCS_OFFICIAL_FIRMWARE" in legacy_text:
            legacy_environment.unlink()

    (variant_directory / f"{environment}.ini").write_text(
        "; Generated by Akita Smart City Services. Re-run the installer to update.\n"
        f"[env:{environment}]\n"
        f"extends = env:{args.base_env}\n"
        "build_flags =\n"
        f"  ${{env:{args.base_env}.build_flags}}\n"
        + "\n".join(flags)
        + "\n"
        "lib_deps =\n"
        + "\n".join(dependencies)
        + "\n",
        encoding="utf-8",
    )
    print(environment)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
